# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # scan(
    #     scheme: 'Runner',
    #     clean: true,
    #     skip_detect_devices: true,
    #     build_for_testing: true,
    #     sdk: 'iphoneos',
    #     should_zip_build_products: true
    # )
    # upload_to_testflight
  end
end
